C#/HDeLeon/ASPNETMVCHDELEON - copia/ASPNETMVCHDELEON/Models/BeerYbrandContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using MVC.Models;

namespace ASPNETMVCHDELEON.Models;

public partial class BeerYbrandContext : DbContext
{
    public BeerYbrandContext()
    {
    }

    public BeerYbrandContext(DbContextOptions<BeerYbrandContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<Cerveza> Cervezas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Brand>(entity =>
        {
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Cerveza>(entity =>
        {
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Brand).WithMany(p => p.Cervezas)
                .HasForeignKey(d => d.BrandId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ClaveUnidora");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

C#/HDeLeon/ASPNETMVCHDELEON - copia/ASPNETMVCHDELEON/Models/Brand.cs
using MVC.Models;
using System;
using System.Collections.Generic;

namespace ASPNETMVCHDELEON.Models;

public partial class Brand
{
    public int BrandId { get; set; }

    public string? Name { get; set; }

    public virtual ICollection<Cerveza> Cervezas { get; set; } = new List<Cerveza>();
}

C#/HDeLeon/ASPNETMVCHDELEON - copia/ASPNETMVCHDELEON/Models/Cerveza.cs
using ASPNETMVCHDELEON.Models;

namespace MVC.Models
{
    public partial class Cerveza
    {
        public int CervezaId { get; set; }

        public string Name { get; set; } = null!;

        public int BrandId { get; set; }

        public virtual Brand Brand { get; set; } = null!;
    }
}

C#/HDeLeon/ASPNETMVCHDELEON - copia/ASPNETMVCHDELEON/Models/ErrorViewModel.cs
namespace ASPNETMVCHDELEON.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

C#/HDeLeon/ASPNETMVCHDELEON - copia/ASPNETMVCHDELEON/Models/ViewModel/CervezaViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ASPNETMVCHDELEON.Models.ViewModel
{
    public class CervezaViewModel
    {
        [Required]
        [Display (Name="Nombre")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Marca")]
        public int BrandId { get; set; }
       
    }
}

C#/HDeLeon/ASPNETMVCHDELEON - copia/ASPNETMVCHDELEON/Controllers/ApiBeerController.cs
using ASPNETMVCHDELEON.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ASPNETMVCHDELEON.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ApiBeerController : ControllerBase
    {
        private readonly BeerYbrandContext _context;
        public ApiBeerController(BeerYbrandContext context)
        {
            _context = context;
        }
        public async Task<List<ObjPrint>> GetCerveza()
        {          
            List<ObjPrint> imprimibles=new List<ObjPrint>();
            
            foreach (var item in _context.Cervezas)
            {                
                imprimibles.Add(new ObjPrint(item.Name,item.Brand.Name,item.CervezaId));
            }
           
            return  imprimibles.ToList();
        }
    }


    public class ObjPrint
    {
        public ObjPrint(string name, string marca, int id) 
        { 
            Name = name;
            Marca = marca;
            ID= id;
        
        }
        public string Name { get; set; }
        public int ID { get; set; }
        public string Marca { get; set; }
    }
}

C#/HDeLeon/ASPNETMVCHDELEON - copia/ASPNETMVCHDELEON/Controllers/BrandController.cs
using ASPNETMVCHDELEON.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ASPNETMVCHDELEON.Controllers
{
    public class BrandController : Controller
    {
        private readonly BeerYbrandContext _context;
        
        public BrandController(BeerYbrandContext context)
        {
            _context = context;
        }
        public async Task <IActionResult> Index()
        {
            return View(await _context.Brands.ToListAsync());
        }
    }
}

C#/HDeLeon/ASPNETMVCHDELEON - copia/ASPNETMVCHDELEON/Controllers/CervezaController.cs
using ASPNETMVCHDELEON.Models;
using ASPNETMVCHDELEON.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Migrations.Operations;
using Microsoft.EntityFrameworkCore.Scaffolding;
using MVC.Models;
using System.Collections.Immutable;

namespace ASPNETMVCHDELEON.Controllers
{
    public partial class CervezaController : Controller
    {
        private readonly BeerYbrandContext _context;

        public CervezaController(BeerYbrandContext context)
        {
            _context = context;
        }

        public async Task <IActionResult> Index()
        {
            var beers = _context.Cervezas.Include(b => b.Brand);
            return View(await beers.ToListAsync());
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["Brands"] = new SelectList(_context.Brands, "BrandId", "Name" );
            return View(); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> Create(CervezaViewModel model)
        {/*
            if(ModelState.IsValid)
            {
                var beer = new Cerveza()
                {
                    Name = model.Name,
                    BrandId = model.BrandId,                   
                  
                };
                //Opción larga y opción corta:
                _context.Cervezas.Add(beer);
                //_context.Add(beer);
                //Con esta última se agrega a la BBDD con EF:
                await _context.SaveChangesAsync();
                //Index es el método de arriba, que te lleva a la viste de la tabla de cervezas
                return RedirectToAction(nameof(Index));

            }

            ViewData["Brands"] = new SelectList(_context.Brands, "BrandId", "Name", model.BrandId);
            */
            return View(model);
        }
    }
}

C#/HDeLeon/ASPNETMVCHDELEON - copia/ASPNETMVCHDELEON/Controllers/HomeController.cs
using ASPNETMVCHDELEON.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASPNETMVCHDELEON.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

C#/HDeLeon/ASPNETMVCHDELEON - copia/ASPNETMVCHDELEON/Views/Cerveza/Create.cshtml
@using ASPNETMVCHDELEON.Models.ViewModel;
@model CervezaViewModel

<h1> Crear cerveza</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <select asp-for="BrandId" class="form-control" asp-items="ViewBag.Brands"></select>
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>           
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

C#/HDeLeon/ASPNETMVCHDELEON - copia/ASPNETMVCHDELEON/Views/Cerveza/Index.cshtml
@using MVC.Models;
@model List<Cerveza>

<h1>Cervezas</h1>
<p>
    <a asp-action="Create"> Crear </a>"
</p>
<table class="table table-striped">

    <thead>
        <tr>
            <th>Nombre</th>
            <th>Marca</th>
            <th> </th>
        </tr>
    </thead>
    <tbody>
         @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(m=>item.Name)
                </td>
                <td>
                    @Html.DisplayFor(m=>item.Brand.Name)
                </td>               

            </tr>
        }
    </tbody>

</table>

C#/HDeLeon/ASPNETMVCHDELEON - copia/ASPNETMVCHDELEON/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPNETMVCHDELEON</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPNETMVCHDELEON.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPNETMVCHDELEON</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="index">Marca</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cerveza" asp-action="index">Cervezas</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASPNETMVCHDELEON - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>